{% set name = "fasttext" %}
{% set version = "0.2.0" %}
{% set sha256 = "71d24ffec9fcc4364554ecac2b3308d834178c903d16d090aa6be9ea6b8e480c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/facebookresearch/fastText/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - fasttext supervised -h || [[ $? == 1 ]]  # -h returns 1

about:
  home: https://fasttext.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - JungeAlexander
